import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1280, height: 900 } })
await p.goto(process.env.APP_URL)
await p.getByText('Peace & Quiet').click()
await p.getByRole('button', { name: 'Continue' }).click()
await p.waitForTimeout(500)
await p.fill('input[value="01/09/2026"]', '20/12/2026')
const inputs = p.locator('input')
await inputs.nth(1).fill('27/12/2026')
const budgetInput = p.locator('input[type="number"]').first()
await budgetInput.fill('250000')
await p.getByLabel('Children').fill('2')
await p.waitForTimeout(300)
await p.getByLabel('Child 1 age').fill('9')
await p.getByLabel('Child 2 age').fill('12')
await p.locator('h1').click()
await p.locator('select').selectOption('Mumbai')
await p.getByRole('button', { name: 'Continue' }).click()
await p.waitForTimeout(500)
await p.getByRole('button', { name: 'Within India Shorter flights' }).click()
await p.waitForTimeout(500)
await p.getByRole('button', { name: 'The hills Cold air, tea' }).click()
await p.waitForTimeout(500)
await p.getByRole('button', { name: 'Quiet, but some life' }).click()
await p.waitForTimeout(500)
await p.getByRole('button', { name: 'Resort comfort Pool, service' }).click()
await p.waitForTimeout(4000)
await p.getByRole('button', { name: 'Not this one — somewhere else' }).click()
await p.waitForTimeout(3000)
await p.getByRole('button', { name: 'Put Manali & Solang back' }).click()
await p.waitForTimeout(2000)
const txt = await p.locator('body').innerText()
console.log(txt.split('\n').slice(0,10).join('\n'))
await p.screenshot({ path: '.agency/screenshots/16-manali-back.png', fullPage: true })
await b.close()
