import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1280, height: 900 } })
p.on('console', m => { if (m.type() === 'error') console.log('CONSOLE ERROR:', m.text()) })
await p.goto(process.env.APP_URL)
await p.waitForTimeout(500)
await p.getByText('Peace & Quiet').click()
await p.getByRole('button', { name: 'Continue' }).click()
await p.waitForTimeout(800)
console.log(await p.locator('body').innerText())
await p.screenshot({ path: '.agency/screenshots/02-after-vibe.png', fullPage: true })
await b.close()
