import { chromium } from 'playwright'
const b = await chromium.launch()
const ctx = await b.newContext({ viewport: { width: 1280, height: 900 } })
const page = await ctx.newPage()
await page.goto('http://localhost:4079')
await page.waitForTimeout(500)
await page.getByRole('button', { name: /Peace & Quiet/ }).click()
await page.getByRole('button', { name: 'Continue' }).click()
await page.waitForTimeout(350)
await page.getByLabel('Start date').fill('2026-12-20')
await page.getByLabel('End date').fill('2026-12-27')
await page.getByLabel(/Total budget/).fill('250000')
await page.getByLabel('Travellers').fill('4')
await page.getByLabel('Flying from').selectOption({ label: 'Mumbai' })
await page.getByRole('button', { name: 'Continue' }).click()
await page.waitForTimeout(400)
for (const n of [/Within India/, /The hills/, /Quiet, but some life/, /Resort comfort/]) {
  await page.getByRole('button', { name: n }).click(); await page.waitForTimeout(350)
}
await page.waitForTimeout(1500)
await page.getByRole('button', { name: /Copy as text/ }).click()
await page.waitForTimeout(700)
const t0 = await page.locator('body').innerText()
console.log('=== COPY PANEL ===')
console.log((t0.match(/Copy your trip[\s\S]*/)||[''])[0].slice(0,1400))
await page.screenshot({ path: '.agency/screenshots/anita-12-copy.png', fullPage: true })
// adjust travellers properly
const inp = page.locator('.adjust input[type="number"], form input').last()
const all = await page.locator('input').all()
for (const i of all) console.log('INPUT', await i.getAttribute('id'), await i.inputValue().catch(()=>''))
const tr = page.locator('#adjust-travellers, input[name="travellers"]').first()
await page.locator('label:has-text("Travellers")').last().scrollIntoViewIfNeeded()
const target = page.getByLabel('Travellers').last()
await target.click(); await target.press('Control+a'); await target.type('5'); await page.waitForTimeout(600)
const hint = await page.locator('body').innerText()
console.log('HINT NOW:', (hint.match(/Update plan[\s\S]{0,80}/)||[''])[0].replace(/\n/g,' | '))
await page.getByRole('button', { name: /Update plan/ }).click({timeout:8000}).catch(e=>console.log('UPDATE BLOCKED:', e.message.slice(0,120)))
await page.waitForTimeout(2000)
const t2 = await page.locator('body').innerText()
console.log('=== AFTER ===')
console.log(t2.slice(0,240))
console.log('BREAK:', (t2.match(/What makes up your[\s\S]*?Per person[\s\S]{0,100}/)||[''])[0])
await page.screenshot({ path: '.agency/screenshots/anita-13-after5.png', fullPage: true })
await b.close()
