import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1280, height: 900 } })
p.on('console', m => { if (m.type() === 'error') console.log('CONSOLE ERROR:', m.text()) })
await p.goto('http://localhost:4079')
await p.waitForTimeout(700)
await p.getByText('Peace & Quiet').click()
await p.getByRole('button', { name: 'Continue' }).click()
await p.waitForTimeout(500)
await p.getByLabel('Start date').fill('2026-12-20')
await p.getByLabel('End date').fill('2026-12-27')
await p.getByLabel(/Total budget/).fill('250000')
await p.getByLabel('Travellers').fill('4')
await p.getByLabel('Flying from').selectOption({ label: 'Mumbai' })
await p.getByRole('button', { name: 'Continue' }).click()
await p.waitForTimeout(600)
await p.getByRole('button', { name: /Within India/ }).click()
await p.waitForTimeout(600)
await p.getByRole('button', { name: /The hills/ }).click()
await p.waitForTimeout(600)
await p.getByRole('button', { name: /Quiet, but some life/ }).click()
await p.waitForTimeout(600)
await p.getByRole('button', { name: /Resort comfort/ }).click()
await p.waitForTimeout(2500)
console.log('=== PLAN ===')
console.log(await p.locator('body').innerText())
console.log('URL:', p.url())
await p.screenshot({ path: '.agency/screenshots/anita-08-plan.png', fullPage: true })
await b.close()
