import { chromium } from 'playwright'
const b = await chromium.launch()
const ctx = await b.newContext({ viewport: { width: 1280, height: 900 } })
const page = await ctx.newPage()
page.on('console', m => { if (m.type()==='error') console.log('CONSOLE ERROR:', m.text()) })
await page.goto('http://localhost:4079')
await page.waitForTimeout(500)
await page.getByRole('button', { name: /Peace & Quiet/ }).click()
await page.getByRole('button', { name: 'Continue' }).click()
await page.waitForTimeout(350)
await page.getByLabel('Start date').fill('2026-12-20')
await page.getByLabel('End date').fill('2026-12-27')
await page.getByLabel(/Total budget/).fill('250000')
await page.getByLabel('Travellers').fill('4')
await page.getByLabel('Flying from').selectOption({ label: 'Mumbai' })
await page.getByRole('button', { name: 'Continue' }).click()
await page.waitForTimeout(400)
for (const n of [/Within India/, /The hills/, /Quiet, but some life/, /Resort comfort/]) {
  await page.getByRole('button', { name: n }).click(); await page.waitForTimeout(350)
}
await page.waitForTimeout(1500)
const before = await page.locator('body').innerText()
console.log('SAVER CARD SAYS:', before.match(/Saver[\s\S]{0,200}/)[0].replace(/\n/g,' | '))
// click "Use this plan"
await page.getByRole('button', { name: /Use this plan/ }).click()
await page.waitForTimeout(2000)
const after = await page.locator('body').innerText()
console.log('=== AFTER USE THIS PLAN ===')
console.log(after.slice(0, 500))
console.log('BREAKDOWN:', (after.match(/What makes up your[\s\S]*?Per person[\s\S]{0,120}/)||[''])[0])
await page.screenshot({ path: '.agency/screenshots/anita-10-saver.png', fullPage: true })
await b.close()
