import { chromium } from 'playwright'
const b = await chromium.launch()
const ctx = await b.newContext({ viewport: { width: 1280, height: 900 }, permissions:['clipboard-read','clipboard-write'] })
const page = await ctx.newPage()
await page.goto('http://localhost:4079')
await page.waitForTimeout(500)
await page.getByRole('button', { name: /Peace & Quiet/ }).click()
await page.getByRole('button', { name: 'Continue' }).click()
await page.waitForTimeout(350)
await page.getByLabel('Start date').fill('2026-12-20')
await page.getByLabel('End date').fill('2026-12-27')
await page.getByLabel(/Total budget/).fill('250000')
await page.getByLabel('Travellers').fill('4')
await page.getByLabel('Flying from').selectOption({ label: 'Mumbai' })
await page.getByRole('button', { name: 'Continue' }).click()
await page.waitForTimeout(400)
for (const n of [/Within India/, /The hills/, /Quiet, but some life/, /Resort comfort/]) {
  await page.getByRole('button', { name: n }).click(); await page.waitForTimeout(350)
}
await page.waitForTimeout(1500)
// Why this trip
await page.getByText('Why this trip').click(); await page.waitForTimeout(600)
const why = await page.locator('body').innerText()
console.log('=== WHY ===')
console.log((why.match(/Why this trip[\s\S]*?What makes up/)||[''])[0])
// Copy as text
await page.getByRole('button', { name: /Copy as text/ }).click()
await page.waitForTimeout(800)
const clip = await page.evaluate(()=>navigator.clipboard.readText())
console.log('=== CLIPBOARD ===')
console.log(clip)
// Adjust: travellers 4 -> 5 same budget
const trav = page.locator('.replan input, input').filter({hasNot:page.locator('x')})
await page.getByLabel('Travellers').last().fill('5')
await page.waitForTimeout(500)
console.log('HINT:', await page.locator('body').innerText().then(t=>(t.match(/Update plan[\s\S]{0,120}/)||[''])[0].replace(/\n/g,' | ')))
await page.getByRole('button', { name: /Update plan/ }).click()
await page.waitForTimeout(2000)
const t2 = await page.locator('body').innerText()
console.log('=== AFTER 5 TRAVELLERS (same budget 250000) ===')
console.log(t2.slice(0,260))
console.log('BREAKDOWN:', (t2.match(/What makes up your[\s\S]*?Per person[\s\S]{0,100}/)||[''])[0])
await page.screenshot({ path: '.agency/screenshots/anita-11-adjust5.png', fullPage: true })
await b.close()
