import { chromium } from 'playwright'
const b = await chromium.launch()
const ctx = await b.newContext({ viewport: { width: 1280, height: 900 }, permissions: ['clipboard-read','clipboard-write'] })
const p = await ctx.newPage()
p.on('console', m => { if (m.type() === 'error') console.log('CONSOLE ERROR:', m.text()) })
await p.goto('http://localhost:4079'); await p.waitForTimeout(400)
await p.getByText('Party', { exact: true }).click()
await p.getByRole('button', { name: 'Continue' }).click(); await p.waitForTimeout(300)
await p.fill('#field-startDate', '2026-11-13'); await p.fill('#field-endDate', '2026-11-16')
await p.fill('#field-budget', '450000'); await p.fill('#field-travellers', '12')
await p.selectOption('#field-origin', 'Delhi')
await p.getByRole('button', { name: 'Continue' }).click(); await p.waitForTimeout(300)
await p.getByText('International', { exact: true }).click(); await p.waitForTimeout(600)
console.log('=== after International ==='); console.log(await p.locator('body').innerText())
await p.screenshot({ path: '.agency/screenshots/kabir-16-intl-q2.png', fullPage: true })
await b.close()
