import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1280, height: 900 } })
await p.goto('http://localhost:4079'); await p.waitForTimeout(400)
await p.getByText('Party', { exact: true }).click()
await p.getByRole('button', { name: 'Continue' }).click(); await p.waitForTimeout(300)
await p.fill('#field-startDate', '2026-11-11'); await p.fill('#field-endDate', '2026-11-15')
await p.fill('#field-budget', '450000'); await p.fill('#field-travellers', '9')
await p.selectOption('#field-origin', 'Delhi')
await p.getByRole('button', { name: 'Continue' }).click(); await p.waitForTimeout(400)
await p.getByRole('button', { name: /Plan my trip now/i }).click(); await p.waitForTimeout(1500)
const tx = await p.locator('body').innerText()
console.log(tx.split('Your days')[1].split('Why this trip')[0])
console.log('--- head ---'); console.log(tx.split('Your days')[0].slice(150))
await p.screenshot({ path: '.agency/screenshots/kabir-23-wed.png', fullPage: true })
await b.close()
