import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1280, height: 800 } })
await p.goto(process.env.APP_URL)
await p.getByText('Party', { exact: true }).click()
await p.waitForTimeout(300)
await p.getByRole('button', { name: 'Continue' }).click()
await p.waitForTimeout(500)
console.log(await p.locator('body').innerText())
await p.screenshot({ path: '.agency/screenshots/03-after-party.png', fullPage: true })
await b.close()
