import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1280, height: 800 } })
await p.context().grantPermissions(['clipboard-read', 'clipboard-write'])
await p.goto(process.env.APP_URL)
await p.getByText('Party', { exact: true }).click()
await p.getByRole('button', { name: 'Continue' }).click()
await p.waitForTimeout(300)
await p.locator('input').nth(0).fill('13/11/2026')
await p.locator('input').nth(1).fill('16/11/2026')
await p.locator('input').nth(2).fill('450000')
await p.locator('input').nth(3).fill('9')
await p.locator('input').nth(4).fill('0')
await p.locator('select').selectOption({ label: 'Delhi' })
await p.getByRole('button', { name: 'Continue' }).click()
await p.waitForTimeout(300)
await p.getByText('Within India', { exact: true }).click()
await p.waitForTimeout(300)
await p.getByText('A city', { exact: true }).click()
await p.waitForTimeout(300)
await p.getByText('A proper city night', { exact: true }).click()
await p.waitForTimeout(300)
await p.getByText('Resort comfort', { exact: true }).click()
await p.waitForTimeout(3000)

await p.getByRole('button', { name: 'Copy as text' }).click()
await p.waitForTimeout(500)
const clip = await p.evaluate(() => navigator.clipboard.readText())
console.log('=== CLIPBOARD CONTENT ===')
console.log(clip)
console.log('=== LENGTH ===', clip.length)
await p.screenshot({ path: '.agency/screenshots/14-after-copy.png', fullPage: true })
await b.close()
