import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1280, height: 800 } })
await p.goto(process.env.APP_URL)
await p.getByText('Party', { exact: true }).click()
await p.getByRole('button', { name: 'Continue' }).click()
await p.waitForTimeout(300)
await p.locator('input').nth(0).fill('13/11/2026')
await p.locator('input').nth(1).fill('16/11/2026')
await p.locator('input').nth(2).fill('450000')
await p.locator('input').nth(3).fill('9')
await p.locator('input').nth(4).fill('0')
await p.locator('select').selectOption({ label: 'Delhi' })
await p.getByRole('button', { name: 'Continue' }).click()
await p.waitForTimeout(300)
await p.getByText('Within India', { exact: true }).click()
await p.waitForTimeout(300)
await p.getByText('A city', { exact: true }).click()
await p.waitForTimeout(300)
await p.getByText('A proper city night', { exact: true }).click()
await p.waitForTimeout(300)
await p.getByText('Resort comfort', { exact: true }).click()
await p.waitForTimeout(3000)
console.log(await p.locator('body').innerText())
await p.screenshot({ path: '.agency/screenshots/10-final-result.png', fullPage: true })
await b.close()
