import { chromium } from 'playwright'
const b = await chromium.launch()
const ctx = await b.newContext({ viewport: { width: 1280, height: 900 }, permissions: ['clipboard-read','clipboard-write'] })
const p = await ctx.newPage()
p.on('console', m => { if (m.type() === 'error') console.log('CONSOLE ERROR:', m.text()) })
await p.goto('http://localhost:4079'); await p.waitForTimeout(400)
await p.getByText('Party', { exact: true }).click()
await p.getByRole('button', { name: 'Continue' }).click(); await p.waitForTimeout(300)
await p.fill('#field-startDate', '2026-11-13'); await p.fill('#field-endDate', '2026-11-16')
await p.fill('#field-budget', '450000'); await p.fill('#field-travellers', '9')
await p.selectOption('#field-origin', 'Delhi')
await p.getByRole('button', { name: 'Continue' }).click(); await p.waitForTimeout(300)
await p.getByText('Within India', { exact: true }).click(); await p.waitForTimeout(250)
await p.getByText('West coast', { exact: true }).click(); await p.waitForTimeout(250)
await p.getByText('Beach shacks', { exact: true }).click(); await p.waitForTimeout(250)
await p.getByText('Resort comfort', { exact: true }).click(); await p.waitForTimeout(1200)
await p.getByRole('button', { name: 'Copy as text' }).click(); await p.waitForTimeout(500)
await p.screenshot({ path: '.agency/screenshots/kabir-11-modal.png' })
const ta = await p.locator('textarea').inputValue()
console.log('===== TEXTAREA ====='); console.log(ta); console.log('===== END '+ta.length+' chars =====')
await p.getByRole('button', { name: 'Copy', exact: true }).click(); await p.waitForTimeout(500)
await p.screenshot({ path: '.agency/screenshots/kabir-12-copied.png' })
console.log('clipboard len', (await p.evaluate(()=>navigator.clipboard.readText())).length)
console.log('btn now:', await p.locator('.modal button, [role=dialog] button').first().innerText().catch(()=>'?'))
await b.close()
