import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1280, height: 900 } })
p.on('console', m => { if (m.type() === 'error') console.log('CONSOLE ERROR:', m.text()) })
const t0 = Date.now()
await p.goto('http://localhost:4079')
await p.waitForTimeout(400)
await p.getByText('Party', { exact: true }).click()
await p.getByRole('button', { name: 'Continue' }).click()
await p.waitForTimeout(300)
await p.fill('#field-startDate', '2026-11-13')
await p.fill('#field-endDate', '2026-11-16')
await p.fill('#field-budget', '450000')
await p.fill('#field-travellers', '9')
await p.selectOption('#field-origin', 'Delhi')
await p.getByRole('button', { name: 'Continue' }).click()
await p.waitForTimeout(300)
await p.getByText('Within India', { exact: true }).click()
await p.waitForTimeout(250)
await p.getByText('West coast', { exact: true }).click()
await p.waitForTimeout(250)
await p.getByText('Beach shacks', { exact: true }).click()
await p.waitForTimeout(250)
await p.getByText('Resort comfort', { exact: true }).click()
await p.waitForTimeout(1500)
console.log('elapsed ms', Date.now()-t0)
console.log(await p.locator('body').innerText())
await p.screenshot({ path: '.agency/screenshots/kabir-09-result.png', fullPage: true })
await p.context().storageState({ path: '.agency/panel/kabir-state.json' })
await b.close()
