import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1280, height: 800 } })
await p.goto(process.env.APP_URL)
await p.getByText('Party', { exact: true }).click()
await p.waitForTimeout(300)
await p.getByText('Peace & Quiet', { exact: true }).click()
await p.waitForTimeout(300)
await p.screenshot({ path: '.agency/screenshots/02-both-vibes.png', fullPage: true })
console.log(await p.locator('body').innerText())
await b.close()
