import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1280, height: 800 } })
await p.goto('http://localhost:4079')
await p.waitForTimeout(400)
await p.getByRole('button', { name: /Beach/ }).click()
await p.getByRole('button', { name: 'Continue' }).click()
await p.waitForTimeout(300)
await p.getByLabel('Start date').fill('2026-10-10')
await p.getByLabel('End date').fill('2026-10-15')
await p.getByRole('button', { name: 'Continue' }).click()
await p.waitForTimeout(400)
for (const label of ['Within India','West coast','Lively','Resort comfort']) {
  await p.getByRole('button', { name: new RegExp('^'+label) }).click()
  await p.waitForTimeout(400)
}
await p.waitForSelector('text=/total/'); await p.waitForTimeout(400)
await p.getByRole('button', { name: 'Start over' }).click()
await p.waitForTimeout(800)
console.log('--- AFTER START OVER ---')
console.log((await p.locator('body').innerText()).slice(0,400))
await p.screenshot({ path: '.agency/screenshots/rohan-12-startover.png', fullPage: true })
// try to get back to basics to see if dates kept
await p.getByRole('button', { name: /Beach/ }).click()
await p.getByRole('button', { name: 'Continue' }).click()
await p.waitForTimeout(500)
console.log('start date now:', await p.getByLabel('Start date').inputValue())
console.log('end date now:', await p.getByLabel('End date').inputValue())
await b.close()
