import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1280, height: 800 } })
p.on('console', m => { if (m.type() === 'error') console.log('CONSOLE ERROR:', m.text()) })
await p.goto('http://localhost:4079')
await p.waitForTimeout(400)
await p.getByRole('button', { name: /Beach/ }).click()
await p.getByRole('button', { name: 'Continue' }).click()
await p.waitForTimeout(300)
await p.getByLabel('Start date').fill('2026-10-10')
await p.getByLabel('End date').fill('2026-10-15')
await p.getByRole('button', { name: 'Continue' }).click()
await p.waitForTimeout(400)
for (const label of ['Within India','West coast','Lively','Resort comfort']) {
  await p.getByRole('button', { name: new RegExp('^'+label) }).click()
  await p.waitForTimeout(500)
}
const t0=Date.now()
await p.waitForSelector('text=/total/', { timeout: 20000 })
console.log('plan render ms after last click:', Date.now()-t0)
await p.waitForTimeout(500)
console.log(await p.locator('body').innerText().then(t=>t.split('Your days')[0]))
console.log('--- ALTS ---')
console.log(await p.locator('body').innerText().then(t=>t.split('Other ways to do this')[1]||''))
await p.screenshot({ path: '.agency/screenshots/rohan-10-westcoast.png', fullPage: true })
await b.close()
